// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package restful

import (
	"github.com/blackhorseya/mundo/pkg/adapterx"
	"github.com/blackhorseya/mundo/pkg/linebotx"
	"github.com/blackhorseya/mundo/pkg/openaix"
	"github.com/blackhorseya/mundo/pkg/transports/httpx"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func New(v *viper.Viper) (adapterx.Servicer, error) {
	server, err := httpx.NewServer()
	if err != nil {
		return nil, err
	}
	messagingApiAPI, err := linebotx.NewClient()
	if err != nil {
		return nil, err
	}
	client, err := openaix.NewClient()
	if err != nil {
		return nil, err
	}
	servicer := newService(server, messagingApiAPI, client)
	return servicer, nil
}

func NewRestful() (adapterx.Restful, error) {
	server, err := httpx.NewServer()
	if err != nil {
		return nil, err
	}
	messagingApiAPI, err := linebotx.NewClient()
	if err != nil {
		return nil, err
	}
	client, err := openaix.NewClient()
	if err != nil {
		return nil, err
	}
	restful := newRestful(server, messagingApiAPI, client)
	return restful, nil
}

// wire.go:

var providerSet = wire.NewSet(httpx.NewServer, linebotx.NewClient, openaix.NewClient)
